name: BausuchtVirus
version: 1.1
main: de.laparudi.bausuchtvirus.BausuchtVirus
author: LapaRudi
api-version: 1.13
description: Abgegrieft's Bausucht-Virus [Remake]

permissions: 
  bausuchtvirus.use:
    description: Rechte f端r Plugin-Info '#Bausuchtvirus'
  bausuchtvirus.start:
    description: Rechte f端r '#startvirus'
  bausuchtvirus.stop:
    description: Rechte f端r '#stopvirus'
  bausuchtvirus.delay:
    description: Rechte f端r '#delay'